# Generated by Django 2.0 on 2018-08-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payable_referral',
            new_name='Payable_referred',
        ),
    ]
