# Generated by Django 2.0 on 2018-07-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expired_Referrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee', models.CharField(max_length=255, null=True)),
                ('referred', models.CharField(max_length=255, null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
