# Generated by Django 2.0 on 2018-09-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('previous_username', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
