# Generated by Django 2.0 on 2018-08-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_expired_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='pay_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
