# Generated by Django 2.0 on 2018-08-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_referrer_pay_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='payable_referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
