# Generated by Django 2.0 on 2018-08-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payable_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable_referral',
            name='previous_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
