# Generated by Django 2.0 on 2018-06-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('testimony', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
