# Generated by Django 2.0 on 2018-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_testimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('plan', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('confirmed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(max_length=255)),
            ],
        ),
    ]
