# Generated by Django 2.0 on 2018-06-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_plan_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='new_date',
            field=models.DateTimeField(max_length=255, null=True),
        ),
    ]
