# Generated by Django 2.0 on 2018-06-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_plan_new_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='profit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
