# Generated by Django 2.0 on 2018-06-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180614_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='new_date',
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
