# Generated by Django 2.0 on 2018-06-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180615_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='date',
        ),
    ]
