# Generated by Django 2.0 on 2018-06-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180615_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='plan',
            new_name='choice',
        ),
    ]
