# Generated by Django 2.0 on 2018-06-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180615_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
