# Generated by Django 2.0 on 2018-06-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cryptocurrency_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='profit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
