# Generated by Django 2.0 on 2018-06-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180615_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='profit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
