# Generated by Django 2.0 on 2018-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_cryptocurrency_lent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='lent',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
