# Generated by Django 2.0 on 2018-06-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20180616_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('choice', models.PositiveIntegerField(null=True)),
                ('lent', models.CharField(blank=True, max_length=255)),
                ('confirmed', models.BooleanField(default=False)),
                ('profit', models.PositiveIntegerField(default=0, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('choice', models.PositiveIntegerField(null=True)),
                ('lent', models.CharField(blank=True, max_length=255)),
                ('confirmed', models.BooleanField(default=False)),
                ('profit', models.PositiveIntegerField(default=0, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='lent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='profit',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
