# Generated by Django 2.0 on 2018-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20180617_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forex',
            old_name='date',
            new_name='deposit_date',
        ),
        migrations.RenameField(
            model_name='oil',
            old_name='date',
            new_name='deposit_date',
        ),
        migrations.AddField(
            model_name='forex',
            name='lend_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oil',
            name='lend_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='lend_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
