# Generated by Django 2.0 on 2018-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20180617_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('plan', models.CharField(max_length=255, null=True)),
                ('withdraw_amount', models.PositiveIntegerField(null=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
