# Generated by Django 2.0 on 2018-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='amount_lent',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
