# Generated by Django 2.0 on 2018-06-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_cryptocurrency_amount_lent'),
    ]

    operations = [
        migrations.AddField(
            model_name='forex',
            name='amount_lent',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='oil',
            name='amount_lent',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
