# Generated by Django 2.0 on 2018-06-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20180619_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='previous_withdraw',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
