# Generated by Django 2.0 on 2018-06-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20180620_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='previous_withdraw',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
