# Generated by Django 2.0 on 2018-06-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_withdraw_previous_withdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee', models.CharField(max_length=255, null=True)),
                ('referred', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
