# Generated by Django 2.0 on 2018-06-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
