# Generated by Django 2.0 on 2018-07-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='amount',
            field=models.PositiveIntegerField(max_length=255, null=True),
        ),
    ]
