# Generated by Django 2.0 on 2018-07-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_referrer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrer',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
