# Generated by Django 2.0 on 2018-07-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20180708_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='forex',
            name='previous_withdraw',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='oil',
            name='previous_withdraw',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
