# Generated by Django 2.0 on 2018-07-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20180708_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='logistics',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
