# Generated by Django 2.0 on 2018-07-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_withdraw_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
