# Generated by Django 2.0 on 2018-07-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='logistics',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
